baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'CoursesWyn'
theme = 'PaperMod'

# Disable language in URL
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[permalinks]
  posts = '/:slug/'
  page = '/:slug/'

[params]
  env = 'development'
  description = 'Your site description'
  
  [params.theme]
    hideMainMenu = false
    hideSidebar = false
    hideFooter = false

  [params.assets]
    [params.assets.cdn]
      font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      
  [params.icon]
    font_awesome = "6.4.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false
    style = 'github'

[imaging]
  quality = 85
  anchor = 'smart'
  resampleFilter = 'CatmullRom'