baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "CoursesWyn"
theme = "PaperMod"

[params]
  env = "production"
  description = "Discover the best Udemy courses and online learning resources"
  mainSections = ["posts"]
  enablePostNavigationLinks = true

  [params.theme]
    hideMainMenu = false
    hideSidebar = false
    hideFooter = false

  [params.assets]
    [params.assets.cdn]
      font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
      
  [params.icon]
    font_awesome = "6.4.0"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[imaging]
  quality = 85
  anchor = 'smart'
  resampleFilter = 'CatmullRom'

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = '/:slug/'
  page = '/:slug/'

