[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"  # Match your local Hugo version
  NODE_VERSION = "20"       # Or your preferred Node.js version

[[redirects]]
  from = "/*"
  to = "/:splat"
  status = 200

# Redirect www to non-www (or vice versa)
[[redirects]]
  from = "https://www.courseswyn.com/*"
  to = "https://courseswyn.com/:splat"
  status = 301